---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: all
  remote_user: vagrant
  become: yes

  roles:
    - sfromm.mariadb
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.apache-php-fpm
    - geerlingguy.php-mysql
    - darthwade.wordpress
    

